### ISSUE TITLE
A little issue with REPEAT command

### ISSUE THREAD

**Issue by a-g-n-i-v-a** [CedArctic/ducky2python#2]
I noticed some problem with the REPEAT command. The for loop in Line #76 is creating problem. I am just reporting this issue. 

I just changed it to 
for i in range(int(line[7:]) - 1):

And it is working fine, AFAIK. I think the range was missing and there was an invalid addition of int and str.
Please fix it, as this is present in the ducky2python as well

**Comment by CedArctic** [comment]
@a-g-n-i-v-a thank you for pointing this out! I'll fix it right away.
